create table meals (id bigint generated by default as identity, restaurant_id bigint, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table restaurants (id bigint generated by default as identity, email varchar(320) not null unique, cnpj char(14) unique, name varchar(255) not null, picture varchar(255), primary key (id));
alter table if exists meals add constraint FKbgjh8qhpl94lso4d5l6nbiyry foreign key (restaurant_id) references restaurants;
